<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

namespace Customer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>customer.CustomerRequest.Address</code>
 */
class CustomerRequest_Address extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string street = 1;</code>
     */
    private $street = '';
    /**
     * <code>string city = 2;</code>
     */
    private $city = '';
    /**
     * <code>string state = 3;</code>
     */
    private $state = '';
    /**
     * <code>string zip = 4;</code>
     */
    private $zip = '';
    /**
     * <code>bool isShippingAddress = 5;</code>
     */
    private $isShippingAddress = false;

    public function __construct() {
        \GPBMetadata\Customer::initOnce();
        parent::__construct();
    }

    /**
     * <code>string street = 1;</code>
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * <code>string street = 1;</code>
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->street = $var;
    }

    /**
     * <code>string city = 2;</code>
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * <code>string city = 2;</code>
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;
    }

    /**
     * <code>string state = 3;</code>
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * <code>string state = 3;</code>
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->state = $var;
    }

    /**
     * <code>string zip = 4;</code>
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * <code>string zip = 4;</code>
     */
    public function setZip($var)
    {
        GPBUtil::checkString($var, True);
        $this->zip = $var;
    }

    /**
     * <code>bool isShippingAddress = 5;</code>
     */
    public function getIsShippingAddress()
    {
        return $this->isShippingAddress;
    }

    /**
     * <code>bool isShippingAddress = 5;</code>
     */
    public function setIsShippingAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->isShippingAddress = $var;
    }

}

