<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

namespace Customer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request message for filtering Customers.
 * </pre>
 *
 * Protobuf type <code>customer.CustomerFilter</code>
 */
class CustomerFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string keyword = 1;</code>
     */
    private $keyword = '';

    public function __construct() {
        \GPBMetadata\Customer::initOnce();
        parent::__construct();
    }

    /**
     * <code>string keyword = 1;</code>
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * <code>string keyword = 1;</code>
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;
    }

}

